channels:
- conda-forge
dependencies:
- python=3.12.10
- pip<=24.0
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==24.0
  - psutil==5.9.8
  - pyyaml==6.0.1
  - scikit-learn==1.5.1
  - scipy==1.12.0
  - typing-extensions==4.10.0
name: mlflow-env
